Everything Works
Advanced-Memory-Analytics/proc-stat pull request #7
Opened 2024-04-16 18:56 UTC by JasonTanita

Debugged monitoring system. Able to correctly track creation, deletion and changing of PID's

2024-04-16 20:22 UTC, cfbeard requested changes
This looks really good!  I know I left a lot of comments but that is normal for a big PR.  Please use the reply option in the comments, I want your thoughts since some of the things are design decisions.

2024-04-16 20:22 UTC, cfbeard commented on pkg/proc/process.go
> +			}
Why is the sleep here instead of further down?  I would think you would want the sleep to apply to the infinite loop, not the looping through each process?

2024-04-16 20:22 UTC, cfbeard commented on pkg/proc/command.sh
I don't think you use this anymore?  If not just delete it.

2024-04-16 20:22 UTC, cfbeard commented on pkg/proc/process.go
> +}
Probably want to test the children gathering as well.  Can use pgrep -P <Ppid> to get the children of a process and check it against the map.  This is pretty important for setting up monitoring groups, so we should make sure it works.

2024-04-16 20:22 UTC, cfbeard commented on pkg/proc/process_test.go
> +			t.Errorf("Expected application termination detection for PID %d, got: %s", cmd1_PID, msg)
Generally don't want to && test cases like this because then it doesn't actually ensure something is being tested.  For example, this test never actually tests the (defunct) message as that if statement is never entered.  I understand it might be hard to test that case, but it would be better to not include it.  If you wanted, you could just manually set a process's arg map like process.Args["defunct"] = "true".  That way you ensure that you are actually testing that if block.  And then break it into the two cases.

2024-04-16 20:22 UTC, cfbeard commented on pkg/proc/process_test.go
> +	}
Same for the other test.  We don't really need to do benchmarks here.  If we needed to run a debugger for example, this would almost always fail because the debugger would stop execution at a breakpoint, 2 seconds would most likely pass, and then the test would fail.

2024-04-16 20:22 UTC, cfbeard commented on pkg/proc/process_test.go
> +	}
See above.

2024-04-18 03:28 UTC, JasonTanita commented on pkg/proc/process.go
> +			}
Good catch, brought the sleep command outside of the loop.

2024-04-18 03:28 UTC, JasonTanita commented on pkg/proc/command.sh
Deleted

2024-04-18 03:30 UTC, JasonTanita commented on pkg/proc/process_test.go
> +	}
Fair point, removed the time after cases

2024-04-18 03:35 UTC, JasonTanita commented on pkg/proc/process_test.go
> +	}
removed

2024-04-18 03:37 UTC, JasonTanita commented on pkg/proc/process_test.go
> +			t.Errorf("Expected application termination detection for PID %d, got: %s", cmd1_PID, msg)
Removed defunct test case

2024-04-18 04:33 UTC, JasonTanita commented on pkg/proc/process.go
> +func MonitorPIDChanges(interval time.Duration, stopChan <-chan struct{}, cmd string, detectedChan chan<- string, argFilters ...string) {
I like this idea, I will definitely look into a way of refactoring the current code to this.

2024-04-18 07:14 UTC, hktrib commented
I concur with the changes Camden asked for. 

**Currently investing the circumstances behind why my tests were failing. I had a docker daemon process running on an port for a couple days, and it kept finding that as the new application and failing the test, because it wasn't the expected PID.**

What's missing here is a **diagram/good documentation** for **why and how this works and what cases are being protected/handled.** 

I think an immediate sub 1hr/ action item would be to take a look at the relevant part of the exporter diagram and create a in-depth focused part.

2024-04-19 23:07 UTC, cfbeard commented on pkg/proc/process_test.go
> +		MonitorPIDChanges(interval, stopChan, "", detectedChan)
Maybe pass "bash" here because it seems this might cause the test to fail if there is another process on the tests machine that has a -name argument.

2024-04-19 23:07 UTC, cfbeard commented on pkg/proc/process_test.go
> +		MonitorPIDChanges(interval, stopChan, "", detectedChan)
Same here, pass "bash" for cmd.

2024-04-20 02:16 UTC, JasonTanita commented on pkg/proc/process_test.go
> +		MonitorPIDChanges(interval, stopChan, "", detectedChan)
Resolved

2024-04-20 02:16 UTC, JasonTanita commented on pkg/proc/process_test.go
> +		MonitorPIDChanges(interval, stopChan, "", detectedChan)
Resolved

2024-04-20 04:44 UTC, closed without merging